### ISSUE TITLE
404 Error when trying to reach the template's glossary

### ISSUE THREAD

**Issue by ManonMarchand** [carpentries/workbench-template-md#20]
Hi all, thanks for this template, it looks beautiful!

When going on [the website of the template](https://carpentries.github.io/workbench-template-md/ "https://carpentries.github.io/workbench-template-md/"), the `Glossary` option in the top menu leads to a 404 file not found page.

Is there something missing or a wrong link?  

Have a nice day, 
Manon

**Comment by zkamvar** [comment]
Thank you for spotting this! It is a bug: https://github.com/carpentries/sandpaper/issues/401

I will be sure to fix this soon.

**Comment by ManonMarchand** [comment]
On the website, I also cannot click on the search bar to enter my search terms.

**Comment by ManonMarchand** [comment]
Ok thanks! :)
