### ISSUE TITLE
Update the lesson status from pre-alpha to beta

### ISSUE THREAD

**Issue by anenadic** [carpentries/workbench-template-md#36]
As this new lesson template (and the corresponding one for Rmarkdown https://carpentries.github.io/workbench-template-rmd/) has now been thoroughly tested and is the official lesson templates for The Carpentries since May 2023 - perhaps bump the template status to beta @zkamvar? Otherwise, it may be misleading and people not intimately familiar with its development and use may think it is not ready for wider use.

**Comment by tobyhodges** [comment]
Thanks for asking the question, @anenadic. The logic for keeping the status at pre-alpha for this template is that we expect it to be used to start a brand new lesson from scratch, i.e. we are pre-empting the pre-alpha status of the lesson that will be built from the template. By doing this, we save the lesson developer from needing to adjust the life cycle stage when they first start using the template.

**Comment by froggleston** [comment]
I presume that the topic is set to "Alpha" in this repo to also act as a reminder when the new repo is generated? If so, I agree with @anenadic that some clarification would be useful. If this is correct, let me know and I can go ahead and make some edits?

**Comment by tobyhodges** [comment]
Thanks @froggleston. I think the best thing to do is remove the 'alpha' tag from the repository description and to update the README to clarify that the template is ready to be used. Equivalent changes would also need to be made on the R Markdown template repo https://github.com/carpentries/workbench-template-rmd

I will open PRs to make these changes, but I do not have sufficient access to adjust the topics in the repository _About_ box - could you do that please, Rob?

**Comment by froggleston** [comment]
Yup, no problem 👍
